version: '3'

services:
  ko-alpaca-lingo:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: "0"
    image: ko-alpaca-lingo
    shm_size: '64gb'
    command: generate.py --load_8bit --base_model $BASE_MODEL --lora_weights 'tloen/ko-alpaca-lingo-7b'
    restart: unless-stopped
    volumes:
      - ko-alpaca-lingo:/root/.cache # Location downloaded weights will be stored
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

volumes:
  ko-alpaca-lingo:
    name: ko-alpaca-lingo
